export { retencionesForm } from "./retenciones"
export { auditoriaPrewelcomeForm } from "./auditoria-prewelcome"
export { welcomeForm } from "./welcome"
export { equipoComercialForm } from "./comercial"
export { rechazoDebitoForm } from "./rechazo-debito"
export { gestionFcrForm } from "./gestion-fcr"
export { otrasGestionesForm } from "./otras-gestiones"