import { FormConfig } from "@/components/formgenerator";

export const otrasGestionesForm: FormConfig = {
  title: "Otras Gestiones",
  fields: [
    { name: "correo", label: "Correo electrónico", type: "text", required: true },
    { name: "hora_inicio", label: "Hora inicio de gestión", type: "text", required: true },

    {
      name: "pais",
      label: "País",
      type: "select",
      required: true,
      options: [
        { label: "Colombia", value: "colombia" },
        { label: "Chile", value: "chile" },
        { label: "Ecuador", value: "ecuador" },
        { label: "Perú", value: "peru" },
      ],
    },

    { name: "san_cedula_nit", label: "SAN, Cédula o NIT", type: "text", required: true },

    {
      name: "medio_contacto",
      label: "Medio de contacto",
      type: "select",
      options: [
        { label: "Llamada Estaqueue", value: "estaqueue" },
        { label: "Llamada WhatsApp", value: "llamada_whatsapp" },
        { label: "Llamada de entrada", value: "entrada" },
        { label: "WhatsApp (Celular/web/APP)", value: "whatsapp" },
        { label: "Email", value: "email" },
        { label: "Mesa operativa", value: "mesa" },
        { label: "Meet", value: "meet" },
        { label: "No aplica", value: "na" },
      ],
    },

    {
      name: "tipo_gestion",
      label: "Tipo de gestión",
      type: "select",
      required: true,
      options: [
        { label: "Actualización de datos en Salesforce", value: "datos_salesforce" },
        { label: "Análisis SAN", value: "analisis_san" },
        { label: "Asignación de token", value: "asignacion_token" },
        { label: "Auditoría de llamadas", value: "auditoria_llamadas" },
        { label: "Base especial clientes en mora", value: "base_mora" },
        { label: "Base sociodemográfico", value: "base_sociodemografico" },
        { label: "Campaña comercial", value: "campaña_comercial" },
        { label: "Cierre de casos", value: "cierre_casos" },
        { label: "Creación de informes", value: "informes" },
        { label: "Cupones preventa", value: "cupones" },
        { label: "Débito automático / PAT", value: "pat" },
        { label: "Fidelización clientes de zonas de inundaciones Chile", value: "fidelizacion_chile" },
        { label: "Interacción WhatsApp", value: "interaccion_whatsapp" },
        { label: "Llamada entrante a nivel Bambú", value: "llamada_bambu" },
        { label: "SAN cancelada", value: "san_cancelada" },
        { label: "Seguimiento al débito automático / PAT", value: "seguimiento_pat" },
        { label: "Pre Welcome – auditoría", value: "prewelcome_auditoria" },
        { label: "Pre Welcome – seguimiento órdenes", value: "prewelcome_ordenes" },
        { label: "Pre Welcome – descarga de nuevas órdenes", value: "prewelcome_descarga" },
        { label: "Pre Welcome – asignación base seguimiento", value: "prewelcome_asignacion" },
        { label: "Pre Welcome – Colombia/Ecuador/Perú/Chile", value: "prewelcome_paises" },
        { label: "Pre Welcome – gestión documental", value: "prewelcome_doc" },
        { label: "Pre Welcome – liberadas sin contrato", value: "prewelcome_sin_contrato" },
        { label: "Referencias de pago", value: "referencias_pago" },
        { label: "Reporte caso a soporte técnico", value: "soporte_tecnico" },
        { label: "Reporte SAN Retención - cartera", value: "san_retencion" },
        { label: "Validación Equifax", value: "equifax" },
        { label: "Validación Experian", value: "experian" },
        { label: "Validación Truora", value: "truora" },
        { label: "Welcome – Colombia/Ecuador/Perú/Chile", value: "welcome_paises" },
        { label: "Welcome – seguimiento pago primera factura", value: "welcome_pago" },
        { label: "Welcome – seguimiento a suspensión temporal", value: "welcome_suspension" },
        { label: "Welcome – validación consumo histórico", value: "welcome_consumo" },
        { label: "Validación PYMES", value: "validacion_pymes" },
        { label: "Casos SAC", value: "sac" },
        { label: "FCR – FCR", value: "fcr" },
      ],
    },

    { name: "observacion", label: "Observación", type: "text" },
  ],
};
